#ifndef __CONSTANTS_H__
#define __CONSTANTS_H__

#ifndef DANGER_ZONE_RADIUS
#define DANGER_ZONE_RADIUS 17 
#endif // DANGER_ZONE_RADIUS

#ifndef START_POSITION
#define START_POSITION {300-13.570, 200-9.0554}
#endif // START_POSITION

#ifndef START_ORIENTATION
#define START_ORIENTATION 0
#endif // START_ORIENTATION

#ifndef SOLAR_PANEL_AXIS
#define SOLAR_PANEL_AXIS 200-175.2
#endif // SOLAR_PANEL_AXIS

#define BOT_AVERAGE_WIDTH 30
#define TABLE_WIDTH 3000
#define TABLE_HEIGHT 2000

#endif // __CONSTANTS_H__